version: 2.1

executors:
  g_test:
    docker:
      - image: wwvargas/g_test:0.0.1
    

jobs:
  build:
    executor: g_test
    steps:
      - checkout
      - run: 'mkdir build && cd build && cmake .. && make'
      - persist_to_workspace:
          root: build
          paths: .

  searching_test:
    executor: g_test
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: './build/searchTest'

  sorting_test:
    executor: g_test
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: './build/sortTest'

  math_test:
    executor: g_test
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: './build/mathTest'

  geometry_test:
    executor: g_test
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: './build/geoTest'

  graph_test:
    executor: g_test
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: './build/graphTest'

  biginteger_test:
    executor: g_test
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: './build/bigIntegerTest'
  
  global_test:
    executor: g_test
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: './build/globalTest'
  

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - searching_test:
        requires:
          - build
      - sorting_test:
        requires:
          - build
      - math_test:
        requires:
          - build
      - geometry_test:
        requires:
          - build
      - graph_test:
          requires:
            - build
      - biginteger_test:
          requires:
            - build
      - global_test:
          requires:
            - searching_test
            - sorting_test
            - math_test
            - geometry_test
            - graph_test
            - biginteger_test
      
      
