version: 2
jobs:
 build:
   docker:
     - image: wwvargas/g_test:0.0.1
   steps:
     - checkout
     - run: 'mkdir build && cd build && cmake .. && make'
  test:
    docker:
     - image: wwvargas/g_test:0.0.1
    steps:
     - checkout
     - run: './build/globalTest'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
      
