version: 2.1

executors:
  g_test:
    docker:
      - image: wwvargas/g_test:0.0.1
    

jobs:
  build:
    executor: g_test
    steps:
      - checkout
      - run: 'mkdir build && cd build && cmake .. && make'
      - persist_to_workspace:
          root: build
          paths: .
  test:
    executor: g_test
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: './build/globalTest'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      
