version: 2
jobs:
 build:
   docker:
     - image: wwvargas/g_test:0.0.1
   steps:
     - checkout
     - run: 
        name: Building code
        command: 'mkdir build && cd build && cmake .. && make'
     - run:
        name: Running tests
        command: './globalTest'
   